name: Spawn
main: ru.konus.main.Main
version: 1.0.1
author: Konus
description: Плагин для установки и телепорта спавна.
commands:
  spawn:
    description: Телепортироваться на спавн.
    aliases: [спавн]
    usage: /spawn
  setspawn:
    description: Установить спавн.
    usage: /setspawn
  hide:
    description: Скрыть/Расскрыть игроков.
    aliases: [скрыть]
    usage: /hide